---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Copy files
  become: true
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz
- name: Unarchive
  become: true
  shell : |
      cd /home/ubuntu/
      tar xvzf artifact.tar.gz -C .

- name: "run server"
  become: true
  shell : |
      cd /home/ubuntu/
      npm install
      pm2 stop default
      pm2 start npm -- start

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

# - name: "Configure pm2 to start as service"
#   become: true
#   shell: |
#     env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu